### PR TITLE
Add more options on how to run python process

### PR DESCRIPTION
**Pull request by radeinla**
This unfortunately adds a dependency because I was too lazy to do it in pure python. I'm not sure what your philosophy is for dependencies/dependency management but I included a `requirements.txt` file for `pip` users that people can use to install the python deps correctly. I can also probably create a python package for it when I have time. I can make the daemon work with no `daemonize` installed but as I have said, I didn't have the time to do it.

### CODE REVIEW

**Comment by afaqurk** [comment]
Ah man, this puts me in a difficult position. I really like the intent and idea behind this PR.

But Linux Dash is intended to be minimalist. Adding dependencies is avoided for that reason. A Linux Dash server implementation needs to be self contained. Part of the effort in the [dev v2.0 branch](https://github.com/afaqurk/linux-dash/tree/v2.0) will be to enforce that across all of the server implementation.

I will think on how to incorporate the idea to deamonize the server processes in the [v2.0 branch](https://github.com/afaqurk/linux-dash/tree/v2.0) as well. Please feel welcome to contribute any PRs to that branch.

Thanks for taking the time to write this.

**Comment by radeinla** [comment]
@afaqurk That's ok. I daemonized it so that I can put it inside `initd`. Thanks for letting me know. Last Q: will you be providing a python packge on `v2.0` or is it still gonna be only a script? I saw that for node, you provided a node package (I'm not totally sure). Thanks!

**Comment by afaqurk** [comment]
There is no node "package". There is a `package.json` which lists the dependencies of the node server. In the `2.0` release, the goal is to get rid of the `package.json` for the node server and have no dependencies.

All of the Linux Dash server implementations are planned to remain individual scripts. When Linux Dash is bundled into an executable or a daemonized process, it will be a different effort from `v2.0` milestone.

Please let me know if that doesn't answer your question.

**Comment by radeinla** [comment]
Yes, that makes sense. 👍

**Pull request closed without merging**
