### PR TITLE
Custom Express port with an environment variable

### PR DESCRIPTION
**Pull request by Simounet**
Hi there,
First of all, thanks for this great piece of software! I didn't find that handy to edit sources to change the Express port. Now, you can do that on the fly with the `PORT` env var.

Have a nice day.

### CODE REVIEW

**Comment by afaqurk** [comment]
@Simounet Good thought. Please update this to have a more specific and expressive environment variable name.

Majority of the time, Linux Dash is run on shared service VMs or machines. A generic environment variable name like `PORT` can cause problems.

Something along the lines of `LINUX_DASH_SERVER_PORT` should do.

**Comment by Simounet** [comment]
Fair enough. I didn't want to use a long string but you're right. I updated my code. Can you reopen this PR so it can be updated?

**Comment by afaqurk** [comment]
Apparently GitHub won't allow me to reopen your PR. Something to do with force-push. See below.

screen shot 2016-10-26 at 11 08 32 pm

Apparently there is a workaround: https://github.com/isaacs/github/issues/361#issuecomment-219088644 

Had I known that it would cause such a tedious headache, I would not have closed the PR. Lesson learned.

**Comment by Simounet** [comment]
Don't worry. I put the old comit on. Can you reopen it now?

**Comment by Simounet** [comment]
New commit submitted.

**Comment by afaqurk** [comment]
@Simounet Thank you for submitting the update. I've resolved a trivial conflict on top of your commits.

Improvements like these are very useful.

**Comment by Simounet** [comment]
You're welcome. I love adding code to amazing projects like this one! Have a nice day.

**Pull request merged**
