### PR TITLE
Pre-v1.0 template

### PR DESCRIPTION
**Pull request by as0n**
I'm one of [those guys](https://gitter.im/afaqurk/linux-dash) who preferred the old dashboard template, not being a fan of serif fonts and large spacing between letters. I prefer having a somewhat compact dashboard and having access to a as much information as possible without scrolling.

Anyway I revamped the old dashboard template and add it to the list of already available themes : 
capture d ecran 2015-05-31 a 18 00 20

I didn't use any external library and (since my css is quite a bit larger than the other theme's) I `@import`ed this template's css from a separate file (`theme-old.css`).

### CODE REVIEW

**Comment by afaqurk** [comment]
Very nice. I know a good number of people welcome this commit, as do I.

But before we merge this into master, it needs just a few more finishing touches. Here's what I have so far:

- The theme switcher is now protruding from the top right of the screen, showing the first half of the "winter" theme button. 
- The old theme shows the widgets with excessive margin. 
  - On sections which have 2 or more rows of plugins, this leads to an awkward set of mismatched and breaking columns.  
  - This might have something to do with the flex display on plugins holding div.

After those small changes, this is probably ready for master branch and production use.

Awesome pull request.

**Comment by as0n** [comment]
Sure I'll make these fixes.

I'm not quite sure what you mean about the widgets excessive margins though. Would you rather have fixed-width widgets to ensure that they are all aligned below one-another ?

**Comment by afaqurk** [comment]
No, I mean that the widgets seem to break the columns and are widely spaced. They also seem to be missing the grey color to the header above each plugin. 

Here's a screenshot:

**Comment by afaqurk** [comment]
After a little investigating, if I remove the display: flex; property on #plugins in he CSS, it seems to align a much better.

**Comment by as0n** [comment]
Yes that's the behaviour for `justify-content: space-around`. Maybe we could use `justify-content: flex-start`instead.

**Comment by as0n** [comment]
As stated in my previous comment as opted for `justify-content: flex-start` to display the plugins. Now they appear in a continuous line starting from the left :
capture d ecran 2015-05-31 a 22 55 46

Is that what you suggested ?
Please tell me what you think !

**Comment by as0n** [comment]
@afaqurk any thoughts on these new commits ?
I'd be happy to make any further modifications if you think they are needed.

**Comment by afaqurk** [comment]
Sorry for the delay. 

Yes, the new changes address all of my concerns. Great job, it looks awesome.

**Comment by as0n** [comment]
:+1:

**Pull request merged**
